---
- name: Creating directory for ELK stack files.
  file:
    path: ~/ELK/releases
    state: directory

- name: Adding key for ELK repository.
  apt_key:
    keyserver: pgp.mit.edu
    id: D88E42B4

- name: Adding ELK and JAVA 8 APT repositories.
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    - "ppa:webupd8team/java"

- name: Accepting JAVA 8 License.
  debconf:
    name: oracle-java8-installer
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Installing needed packages.
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
    - apt-transport-https
    - unzip
    - curl
    - elasticsearch
    - logstash
    - kibana
    - openssl
    - python-passlib

- name: Enabling ELK packages.
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - elasticsearch
    - logstash
    - kibana
