---
- name: Checking if certificates where already created.
  stat: path="/etc/letsencrypt/live/www.{{ elk_server_domain }}"
  register: cert

- include: hostname.yml
- include: ssl.yml
  when: not cert.stat.exists
- include: install.yml
- include: configs.yml
  tags: config
