---
- name: Adding Certbot repo.
  apt_repository: repo="ppa:certbot/certbot"

- name: Installing Certbot package.
  apt: name=python-certbot-nginx

- name: Creating directory for Certbot tests.
  file:
    dest: /var/www/html/.well-known/acme-challenge
    state: directory

- name: Adding LetsEncrypt config file.
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini

- name: Adding Nginx cert config.
  template:
    src: default-cert.j2
    dest: /etc/nginx/sites-available/default

- name: Restarting Nginx.
  service: name=nginx state=restarted

- name: Receiving LetsEncrypt certificates.
  command: >
    certbot certonly --agree-tos -n -m {{ elk_ssl_email }} -d {{ elk_server_domain }} 
